/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import {
  ethers,
  EventFilter,
  Signer,
  BigNumber,
  BigNumberish,
  PopulatedTransaction,
} from "ethers";
import {
  Contract,
  ContractTransaction,
  Overrides,
  PayableOverrides,
  CallOverrides,
} from "@ethersproject/contracts";
import { BytesLike } from "@ethersproject/bytes";
import { Listener, Provider } from "@ethersproject/providers";
import { FunctionFragment, EventFragment, Result } from "@ethersproject/abi";

interface BaalSummonerInterface extends ethers.utils.Interface {
  functions: {
    "deployModule(address,bytes,uint256)": FunctionFragment;
    "encodeMultisend(bytes[],address)": FunctionFragment;
    "gnosisFallbackLibrary()": FunctionFragment;
    "gnosisMultisendLibrary()": FunctionFragment;
    "gnosisSingleton()": FunctionFragment;
    "lootSingleton()": FunctionFragment;
    "optionalSusReceiver()": FunctionFragment;
    "sharesSingleton()": FunctionFragment;
    "summonBaal(bytes,bytes[],uint256)": FunctionFragment;
    "summonBaalAndSafe(bytes,bytes[],uint256)": FunctionFragment;
    "template()": FunctionFragment;
  };

  encodeFunctionData(
    functionFragment: "deployModule",
    values: [string, BytesLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "encodeMultisend",
    values: [BytesLike[], string]
  ): string;
  encodeFunctionData(
    functionFragment: "gnosisFallbackLibrary",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "gnosisMultisendLibrary",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "gnosisSingleton",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "lootSingleton",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "optionalSusReceiver",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "sharesSingleton",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "summonBaal",
    values: [BytesLike, BytesLike[], BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "summonBaalAndSafe",
    values: [BytesLike, BytesLike[], BigNumberish]
  ): string;
  encodeFunctionData(functionFragment: "template", values?: undefined): string;

  decodeFunctionResult(
    functionFragment: "deployModule",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "encodeMultisend",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "gnosisFallbackLibrary",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "gnosisMultisendLibrary",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "gnosisSingleton",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "lootSingleton",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "optionalSusReceiver",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "sharesSingleton",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "summonBaal", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "summonBaalAndSafe",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "template", data: BytesLike): Result;

  events: {
    "ModuleProxyCreation(address,address)": EventFragment;
    "SummonBaal(address,address,address,address)": EventFragment;
  };

  getEvent(nameOrSignatureOrTopic: "ModuleProxyCreation"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "SummonBaal"): EventFragment;
}

export class BaalSummoner extends Contract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  on(event: EventFilter | string, listener: Listener): this;
  once(event: EventFilter | string, listener: Listener): this;
  addListener(eventName: EventFilter | string, listener: Listener): this;
  removeAllListeners(eventName: EventFilter | string): this;
  removeListener(eventName: any, listener: Listener): this;

  interface: BaalSummonerInterface;

  functions: {
    deployModule(
      masterCopy: string,
      initializer: BytesLike,
      saltNonce: BigNumberish,
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    "deployModule(address,bytes,uint256)"(
      masterCopy: string,
      initializer: BytesLike,
      saltNonce: BigNumberish,
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    encodeMultisend(
      _calls: BytesLike[],
      _target: string,
      overrides?: CallOverrides
    ): Promise<{
      encodedMultisend: string;
      0: string;
    }>;

    "encodeMultisend(bytes[],address)"(
      _calls: BytesLike[],
      _target: string,
      overrides?: CallOverrides
    ): Promise<{
      encodedMultisend: string;
      0: string;
    }>;

    gnosisFallbackLibrary(overrides?: CallOverrides): Promise<{
      0: string;
    }>;

    "gnosisFallbackLibrary()"(overrides?: CallOverrides): Promise<{
      0: string;
    }>;

    gnosisMultisendLibrary(overrides?: CallOverrides): Promise<{
      0: string;
    }>;

    "gnosisMultisendLibrary()"(overrides?: CallOverrides): Promise<{
      0: string;
    }>;

    gnosisSingleton(overrides?: CallOverrides): Promise<{
      0: string;
    }>;

    "gnosisSingleton()"(overrides?: CallOverrides): Promise<{
      0: string;
    }>;

    lootSingleton(overrides?: CallOverrides): Promise<{
      0: string;
    }>;

    "lootSingleton()"(overrides?: CallOverrides): Promise<{
      0: string;
    }>;

    optionalSusReceiver(overrides?: CallOverrides): Promise<{
      0: string;
    }>;

    "optionalSusReceiver()"(overrides?: CallOverrides): Promise<{
      0: string;
    }>;

    sharesSingleton(overrides?: CallOverrides): Promise<{
      0: string;
    }>;

    "sharesSingleton()"(overrides?: CallOverrides): Promise<{
      0: string;
    }>;

    summonBaal(
      initializationParams: BytesLike,
      initializationActions: BytesLike[],
      _saltNonce: BigNumberish,
      overrides?: PayableOverrides
    ): Promise<ContractTransaction>;

    "summonBaal(bytes,bytes[],uint256)"(
      initializationParams: BytesLike,
      initializationActions: BytesLike[],
      _saltNonce: BigNumberish,
      overrides?: PayableOverrides
    ): Promise<ContractTransaction>;

    summonBaalAndSafe(
      initializationParams: BytesLike,
      initializationActions: BytesLike[],
      _saltNonce: BigNumberish,
      overrides?: PayableOverrides
    ): Promise<ContractTransaction>;

    "summonBaalAndSafe(bytes,bytes[],uint256)"(
      initializationParams: BytesLike,
      initializationActions: BytesLike[],
      _saltNonce: BigNumberish,
      overrides?: PayableOverrides
    ): Promise<ContractTransaction>;

    template(overrides?: CallOverrides): Promise<{
      0: string;
    }>;

    "template()"(overrides?: CallOverrides): Promise<{
      0: string;
    }>;
  };

  deployModule(
    masterCopy: string,
    initializer: BytesLike,
    saltNonce: BigNumberish,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  "deployModule(address,bytes,uint256)"(
    masterCopy: string,
    initializer: BytesLike,
    saltNonce: BigNumberish,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  encodeMultisend(
    _calls: BytesLike[],
    _target: string,
    overrides?: CallOverrides
  ): Promise<string>;

  "encodeMultisend(bytes[],address)"(
    _calls: BytesLike[],
    _target: string,
    overrides?: CallOverrides
  ): Promise<string>;

  gnosisFallbackLibrary(overrides?: CallOverrides): Promise<string>;

  "gnosisFallbackLibrary()"(overrides?: CallOverrides): Promise<string>;

  gnosisMultisendLibrary(overrides?: CallOverrides): Promise<string>;

  "gnosisMultisendLibrary()"(overrides?: CallOverrides): Promise<string>;

  gnosisSingleton(overrides?: CallOverrides): Promise<string>;

  "gnosisSingleton()"(overrides?: CallOverrides): Promise<string>;

  lootSingleton(overrides?: CallOverrides): Promise<string>;

  "lootSingleton()"(overrides?: CallOverrides): Promise<string>;

  optionalSusReceiver(overrides?: CallOverrides): Promise<string>;

  "optionalSusReceiver()"(overrides?: CallOverrides): Promise<string>;

  sharesSingleton(overrides?: CallOverrides): Promise<string>;

  "sharesSingleton()"(overrides?: CallOverrides): Promise<string>;

  summonBaal(
    initializationParams: BytesLike,
    initializationActions: BytesLike[],
    _saltNonce: BigNumberish,
    overrides?: PayableOverrides
  ): Promise<ContractTransaction>;

  "summonBaal(bytes,bytes[],uint256)"(
    initializationParams: BytesLike,
    initializationActions: BytesLike[],
    _saltNonce: BigNumberish,
    overrides?: PayableOverrides
  ): Promise<ContractTransaction>;

  summonBaalAndSafe(
    initializationParams: BytesLike,
    initializationActions: BytesLike[],
    _saltNonce: BigNumberish,
    overrides?: PayableOverrides
  ): Promise<ContractTransaction>;

  "summonBaalAndSafe(bytes,bytes[],uint256)"(
    initializationParams: BytesLike,
    initializationActions: BytesLike[],
    _saltNonce: BigNumberish,
    overrides?: PayableOverrides
  ): Promise<ContractTransaction>;

  template(overrides?: CallOverrides): Promise<string>;

  "template()"(overrides?: CallOverrides): Promise<string>;

  callStatic: {
    deployModule(
      masterCopy: string,
      initializer: BytesLike,
      saltNonce: BigNumberish,
      overrides?: CallOverrides
    ): Promise<string>;

    "deployModule(address,bytes,uint256)"(
      masterCopy: string,
      initializer: BytesLike,
      saltNonce: BigNumberish,
      overrides?: CallOverrides
    ): Promise<string>;

    encodeMultisend(
      _calls: BytesLike[],
      _target: string,
      overrides?: CallOverrides
    ): Promise<string>;

    "encodeMultisend(bytes[],address)"(
      _calls: BytesLike[],
      _target: string,
      overrides?: CallOverrides
    ): Promise<string>;

    gnosisFallbackLibrary(overrides?: CallOverrides): Promise<string>;

    "gnosisFallbackLibrary()"(overrides?: CallOverrides): Promise<string>;

    gnosisMultisendLibrary(overrides?: CallOverrides): Promise<string>;

    "gnosisMultisendLibrary()"(overrides?: CallOverrides): Promise<string>;

    gnosisSingleton(overrides?: CallOverrides): Promise<string>;

    "gnosisSingleton()"(overrides?: CallOverrides): Promise<string>;

    lootSingleton(overrides?: CallOverrides): Promise<string>;

    "lootSingleton()"(overrides?: CallOverrides): Promise<string>;

    optionalSusReceiver(overrides?: CallOverrides): Promise<string>;

    "optionalSusReceiver()"(overrides?: CallOverrides): Promise<string>;

    sharesSingleton(overrides?: CallOverrides): Promise<string>;

    "sharesSingleton()"(overrides?: CallOverrides): Promise<string>;

    summonBaal(
      initializationParams: BytesLike,
      initializationActions: BytesLike[],
      _saltNonce: BigNumberish,
      overrides?: CallOverrides
    ): Promise<string>;

    "summonBaal(bytes,bytes[],uint256)"(
      initializationParams: BytesLike,
      initializationActions: BytesLike[],
      _saltNonce: BigNumberish,
      overrides?: CallOverrides
    ): Promise<string>;

    summonBaalAndSafe(
      initializationParams: BytesLike,
      initializationActions: BytesLike[],
      _saltNonce: BigNumberish,
      overrides?: CallOverrides
    ): Promise<string>;

    "summonBaalAndSafe(bytes,bytes[],uint256)"(
      initializationParams: BytesLike,
      initializationActions: BytesLike[],
      _saltNonce: BigNumberish,
      overrides?: CallOverrides
    ): Promise<string>;

    template(overrides?: CallOverrides): Promise<string>;

    "template()"(overrides?: CallOverrides): Promise<string>;
  };

  filters: {
    ModuleProxyCreation(
      proxy: string | null,
      masterCopy: string | null
    ): EventFilter;

    SummonBaal(
      baal: string | null,
      loot: string | null,
      shares: string | null,
      safe: null
    ): EventFilter;
  };

  estimateGas: {
    deployModule(
      masterCopy: string,
      initializer: BytesLike,
      saltNonce: BigNumberish,
      overrides?: Overrides
    ): Promise<BigNumber>;

    "deployModule(address,bytes,uint256)"(
      masterCopy: string,
      initializer: BytesLike,
      saltNonce: BigNumberish,
      overrides?: Overrides
    ): Promise<BigNumber>;

    encodeMultisend(
      _calls: BytesLike[],
      _target: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    "encodeMultisend(bytes[],address)"(
      _calls: BytesLike[],
      _target: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    gnosisFallbackLibrary(overrides?: CallOverrides): Promise<BigNumber>;

    "gnosisFallbackLibrary()"(overrides?: CallOverrides): Promise<BigNumber>;

    gnosisMultisendLibrary(overrides?: CallOverrides): Promise<BigNumber>;

    "gnosisMultisendLibrary()"(overrides?: CallOverrides): Promise<BigNumber>;

    gnosisSingleton(overrides?: CallOverrides): Promise<BigNumber>;

    "gnosisSingleton()"(overrides?: CallOverrides): Promise<BigNumber>;

    lootSingleton(overrides?: CallOverrides): Promise<BigNumber>;

    "lootSingleton()"(overrides?: CallOverrides): Promise<BigNumber>;

    optionalSusReceiver(overrides?: CallOverrides): Promise<BigNumber>;

    "optionalSusReceiver()"(overrides?: CallOverrides): Promise<BigNumber>;

    sharesSingleton(overrides?: CallOverrides): Promise<BigNumber>;

    "sharesSingleton()"(overrides?: CallOverrides): Promise<BigNumber>;

    summonBaal(
      initializationParams: BytesLike,
      initializationActions: BytesLike[],
      _saltNonce: BigNumberish,
      overrides?: PayableOverrides
    ): Promise<BigNumber>;

    "summonBaal(bytes,bytes[],uint256)"(
      initializationParams: BytesLike,
      initializationActions: BytesLike[],
      _saltNonce: BigNumberish,
      overrides?: PayableOverrides
    ): Promise<BigNumber>;

    summonBaalAndSafe(
      initializationParams: BytesLike,
      initializationActions: BytesLike[],
      _saltNonce: BigNumberish,
      overrides?: PayableOverrides
    ): Promise<BigNumber>;

    "summonBaalAndSafe(bytes,bytes[],uint256)"(
      initializationParams: BytesLike,
      initializationActions: BytesLike[],
      _saltNonce: BigNumberish,
      overrides?: PayableOverrides
    ): Promise<BigNumber>;

    template(overrides?: CallOverrides): Promise<BigNumber>;

    "template()"(overrides?: CallOverrides): Promise<BigNumber>;
  };

  populateTransaction: {
    deployModule(
      masterCopy: string,
      initializer: BytesLike,
      saltNonce: BigNumberish,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    "deployModule(address,bytes,uint256)"(
      masterCopy: string,
      initializer: BytesLike,
      saltNonce: BigNumberish,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    encodeMultisend(
      _calls: BytesLike[],
      _target: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    "encodeMultisend(bytes[],address)"(
      _calls: BytesLike[],
      _target: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    gnosisFallbackLibrary(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    "gnosisFallbackLibrary()"(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    gnosisMultisendLibrary(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    "gnosisMultisendLibrary()"(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    gnosisSingleton(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    "gnosisSingleton()"(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    lootSingleton(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    "lootSingleton()"(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    optionalSusReceiver(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    "optionalSusReceiver()"(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    sharesSingleton(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    "sharesSingleton()"(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    summonBaal(
      initializationParams: BytesLike,
      initializationActions: BytesLike[],
      _saltNonce: BigNumberish,
      overrides?: PayableOverrides
    ): Promise<PopulatedTransaction>;

    "summonBaal(bytes,bytes[],uint256)"(
      initializationParams: BytesLike,
      initializationActions: BytesLike[],
      _saltNonce: BigNumberish,
      overrides?: PayableOverrides
    ): Promise<PopulatedTransaction>;

    summonBaalAndSafe(
      initializationParams: BytesLike,
      initializationActions: BytesLike[],
      _saltNonce: BigNumberish,
      overrides?: PayableOverrides
    ): Promise<PopulatedTransaction>;

    "summonBaalAndSafe(bytes,bytes[],uint256)"(
      initializationParams: BytesLike,
      initializationActions: BytesLike[],
      _saltNonce: BigNumberish,
      overrides?: PayableOverrides
    ): Promise<PopulatedTransaction>;

    template(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    "template()"(overrides?: CallOverrides): Promise<PopulatedTransaction>;
  };
}
