/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import {
  ethers,
  EventFilter,
  Signer,
  BigNumber,
  BigNumberish,
  PopulatedTransaction,
} from "ethers";
import {
  Contract,
  ContractTransaction,
  Overrides,
  CallOverrides,
} from "@ethersproject/contracts";
import { BytesLike } from "@ethersproject/bytes";
import { Listener, Provider } from "@ethersproject/providers";
import { FunctionFragment, EventFragment, Result } from "@ethersproject/abi";

interface DhTokenFactoryInterface extends ethers.utils.Interface {
  functions: {
    "summonToken(uint256,string,string,address)": FunctionFragment;
    "template()": FunctionFragment;
  };

  encodeFunctionData(
    functionFragment: "summonToken",
    values: [BigNumberish, string, string, string]
  ): string;
  encodeFunctionData(functionFragment: "template", values?: undefined): string;

  decodeFunctionResult(
    functionFragment: "summonToken",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "template", data: BytesLike): Result;

  events: {
    "SummonToken(address,address)": EventFragment;
  };

  getEvent(nameOrSignatureOrTopic: "SummonToken"): EventFragment;
}

export class DhTokenFactory extends Contract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  on(event: EventFilter | string, listener: Listener): this;
  once(event: EventFilter | string, listener: Listener): this;
  addListener(eventName: EventFilter | string, listener: Listener): this;
  removeAllListeners(eventName: EventFilter | string): this;
  removeListener(eventName: any, listener: Listener): this;

  interface: DhTokenFactoryInterface;

  functions: {
    summonToken(
      supply: BigNumberish,
      name: string,
      symbol: string,
      receiver: string,
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    "summonToken(uint256,string,string,address)"(
      supply: BigNumberish,
      name: string,
      symbol: string,
      receiver: string,
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    template(overrides?: CallOverrides): Promise<{
      0: string;
    }>;

    "template()"(overrides?: CallOverrides): Promise<{
      0: string;
    }>;
  };

  summonToken(
    supply: BigNumberish,
    name: string,
    symbol: string,
    receiver: string,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  "summonToken(uint256,string,string,address)"(
    supply: BigNumberish,
    name: string,
    symbol: string,
    receiver: string,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  template(overrides?: CallOverrides): Promise<string>;

  "template()"(overrides?: CallOverrides): Promise<string>;

  callStatic: {
    summonToken(
      supply: BigNumberish,
      name: string,
      symbol: string,
      receiver: string,
      overrides?: CallOverrides
    ): Promise<string>;

    "summonToken(uint256,string,string,address)"(
      supply: BigNumberish,
      name: string,
      symbol: string,
      receiver: string,
      overrides?: CallOverrides
    ): Promise<string>;

    template(overrides?: CallOverrides): Promise<string>;

    "template()"(overrides?: CallOverrides): Promise<string>;
  };

  filters: {
    SummonToken(token: string | null, receiver: string | null): EventFilter;
  };

  estimateGas: {
    summonToken(
      supply: BigNumberish,
      name: string,
      symbol: string,
      receiver: string,
      overrides?: Overrides
    ): Promise<BigNumber>;

    "summonToken(uint256,string,string,address)"(
      supply: BigNumberish,
      name: string,
      symbol: string,
      receiver: string,
      overrides?: Overrides
    ): Promise<BigNumber>;

    template(overrides?: CallOverrides): Promise<BigNumber>;

    "template()"(overrides?: CallOverrides): Promise<BigNumber>;
  };

  populateTransaction: {
    summonToken(
      supply: BigNumberish,
      name: string,
      symbol: string,
      receiver: string,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    "summonToken(uint256,string,string,address)"(
      supply: BigNumberish,
      name: string,
      symbol: string,
      receiver: string,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    template(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    "template()"(overrides?: CallOverrides): Promise<PopulatedTransaction>;
  };
}
