/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import {
  ethers,
  EventFilter,
  Signer,
  BigNumber,
  BigNumberish,
  PopulatedTransaction,
} from "ethers";
import {
  Contract,
  ContractTransaction,
  Overrides,
  CallOverrides,
} from "@ethersproject/contracts";
import { BytesLike } from "@ethersproject/bytes";
import { Listener, Provider } from "@ethersproject/providers";
import { FunctionFragment, EventFragment, Result } from "@ethersproject/abi";

interface PosterInterface extends ethers.utils.Interface {
  functions: {
    "post(string,string)": FunctionFragment;
  };

  encodeFunctionData(
    functionFragment: "post",
    values: [string, string]
  ): string;

  decodeFunctionResult(functionFragment: "post", data: BytesLike): Result;

  events: {
    "NewPost(address,string,string)": EventFragment;
  };

  getEvent(nameOrSignatureOrTopic: "NewPost"): EventFragment;
}

export class Poster extends Contract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  on(event: EventFilter | string, listener: Listener): this;
  once(event: EventFilter | string, listener: Listener): this;
  addListener(eventName: EventFilter | string, listener: Listener): this;
  removeAllListeners(eventName: EventFilter | string): this;
  removeListener(eventName: any, listener: Listener): this;

  interface: PosterInterface;

  functions: {
    post(
      content: string,
      tag: string,
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    "post(string,string)"(
      content: string,
      tag: string,
      overrides?: Overrides
    ): Promise<ContractTransaction>;
  };

  post(
    content: string,
    tag: string,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  "post(string,string)"(
    content: string,
    tag: string,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  callStatic: {
    post(
      content: string,
      tag: string,
      overrides?: CallOverrides
    ): Promise<void>;

    "post(string,string)"(
      content: string,
      tag: string,
      overrides?: CallOverrides
    ): Promise<void>;
  };

  filters: {
    NewPost(
      user: string | null,
      content: null,
      tag: string | null
    ): EventFilter;
  };

  estimateGas: {
    post(
      content: string,
      tag: string,
      overrides?: Overrides
    ): Promise<BigNumber>;

    "post(string,string)"(
      content: string,
      tag: string,
      overrides?: Overrides
    ): Promise<BigNumber>;
  };

  populateTransaction: {
    post(
      content: string,
      tag: string,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    "post(string,string)"(
      content: string,
      tag: string,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;
  };
}
