/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Signer } from "ethers";
import { Provider, TransactionRequest } from "@ethersproject/providers";
import { Contract, ContractFactory, Overrides } from "@ethersproject/contracts";

import type { RageQuitBank } from "./RageQuitBank";

export class RageQuitBankFactory extends ContractFactory {
  constructor(signer?: Signer) {
    super(_abi, _bytecode, signer);
  }

  deploy(overrides?: Overrides): Promise<RageQuitBank> {
    return super.deploy(overrides || {}) as Promise<RageQuitBank>;
  }
  getDeployTransaction(overrides?: Overrides): TransactionRequest {
    return super.getDeployTransaction(overrides || {});
  }
  attach(address: string): RageQuitBank {
    return super.attach(address) as RageQuitBank;
  }
  connect(signer: Signer): RageQuitBankFactory {
    return super.connect(signer) as RageQuitBankFactory;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): RageQuitBank {
    return new Contract(address, _abi, signerOrProvider) as RageQuitBank;
  }
}

const _abi = [
  {
    inputs: [],
    name: "baal",
    outputs: [
      {
        internalType: "address",
        name: "",
        type: "address",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "_baal",
        type: "address",
      },
    ],
    name: "init",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "",
        type: "address",
      },
      {
        internalType: "uint96",
        name: "loot",
        type: "uint96",
      },
      {
        internalType: "uint96",
        name: "shares",
        type: "uint96",
      },
    ],
    name: "memberAction",
    outputs: [
      {
        internalType: "uint96",
        name: "lootOut",
        type: "uint96",
      },
      {
        internalType: "uint96",
        name: "sharesOut",
        type: "uint96",
      },
    ],
    stateMutability: "payable",
    type: "function",
  },
];

const _bytecode =
  "0x608060405234801561001057600080fd5b506102ba806100206000396000f3fe6080604052600436106100345760003560e01c806319ab453c14610039578063e5a2a2a51461005b578063ff4c988414610098575b600080fd5b34801561004557600080fd5b506100596100543660046101e2565b6100cb565b005b34801561006757600080fd5b5060005461007b906001600160a01b031681565b6040516001600160a01b0390911681526020015b60405180910390f35b6100ab6100a6366004610204565b610148565b604080516001600160601b0393841681529290911660208301520161008f565b6001600160a01b0381166101265760405162461bcd60e51b815260206004820152601e60248201527f7472616e736665722066726f6d20746865207a65726f2061646472657373000060448201526064015b60405180910390fd5b600080546001600160a01b0319166001600160a01b0392909216919091179055565b6000805481906001600160a01b0316331461018d5760405162461bcd60e51b8152602060048201526005602482015264085898585b60da1b604482015260640161011d565b610198600285610247565b91506101a5600284610247565b9050935093915050565b80356001600160a01b03811681146101c657600080fd5b919050565b80356001600160601b03811681146101c657600080fd5b6000602082840312156101f457600080fd5b6101fd826101af565b9392505050565b60008060006060848603121561021957600080fd5b610222846101af565b9250610230602085016101cb565b915061023e604085016101cb565b90509250925092565b60006001600160601b038083168185168183048111821515161561027b57634e487b7160e01b600052601160045260246000fd5b0294935050505056fea2646970667358221220a84bd96888b35c63e4f0ff00d7ef73bae2f680fd3ae0247ee9c9fa030e447ae764736f6c63430008070033";
