/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import {
  ethers,
  EventFilter,
  Signer,
  BigNumber,
  BigNumberish,
  PopulatedTransaction,
} from "ethers";
import {
  Contract,
  ContractTransaction,
  Overrides,
  CallOverrides,
} from "@ethersproject/contracts";
import { BytesLike } from "@ethersproject/bytes";
import { Listener, Provider } from "@ethersproject/providers";
import { FunctionFragment, EventFragment, Result } from "@ethersproject/abi";

interface SignMessageLibInterface extends ethers.utils.Interface {
  functions: {
    "getMessageHash(bytes)": FunctionFragment;
    "signMessage(bytes)": FunctionFragment;
  };

  encodeFunctionData(
    functionFragment: "getMessageHash",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "signMessage",
    values: [BytesLike]
  ): string;

  decodeFunctionResult(
    functionFragment: "getMessageHash",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "signMessage",
    data: BytesLike
  ): Result;

  events: {
    "SignMsg(bytes32)": EventFragment;
  };

  getEvent(nameOrSignatureOrTopic: "SignMsg"): EventFragment;
}

export class SignMessageLib extends Contract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  on(event: EventFilter | string, listener: Listener): this;
  once(event: EventFilter | string, listener: Listener): this;
  addListener(eventName: EventFilter | string, listener: Listener): this;
  removeAllListeners(eventName: EventFilter | string): this;
  removeListener(eventName: any, listener: Listener): this;

  interface: SignMessageLibInterface;

  functions: {
    getMessageHash(
      message: BytesLike,
      overrides?: CallOverrides
    ): Promise<{
      0: string;
    }>;

    "getMessageHash(bytes)"(
      message: BytesLike,
      overrides?: CallOverrides
    ): Promise<{
      0: string;
    }>;

    signMessage(
      _data: BytesLike,
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    "signMessage(bytes)"(
      _data: BytesLike,
      overrides?: Overrides
    ): Promise<ContractTransaction>;
  };

  getMessageHash(
    message: BytesLike,
    overrides?: CallOverrides
  ): Promise<string>;

  "getMessageHash(bytes)"(
    message: BytesLike,
    overrides?: CallOverrides
  ): Promise<string>;

  signMessage(
    _data: BytesLike,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  "signMessage(bytes)"(
    _data: BytesLike,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  callStatic: {
    getMessageHash(
      message: BytesLike,
      overrides?: CallOverrides
    ): Promise<string>;

    "getMessageHash(bytes)"(
      message: BytesLike,
      overrides?: CallOverrides
    ): Promise<string>;

    signMessage(_data: BytesLike, overrides?: CallOverrides): Promise<void>;

    "signMessage(bytes)"(
      _data: BytesLike,
      overrides?: CallOverrides
    ): Promise<void>;
  };

  filters: {
    SignMsg(msgHash: BytesLike | null): EventFilter;
  };

  estimateGas: {
    getMessageHash(
      message: BytesLike,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    "getMessageHash(bytes)"(
      message: BytesLike,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    signMessage(_data: BytesLike, overrides?: Overrides): Promise<BigNumber>;

    "signMessage(bytes)"(
      _data: BytesLike,
      overrides?: Overrides
    ): Promise<BigNumber>;
  };

  populateTransaction: {
    getMessageHash(
      message: BytesLike,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    "getMessageHash(bytes)"(
      message: BytesLike,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    signMessage(
      _data: BytesLike,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    "signMessage(bytes)"(
      _data: BytesLike,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;
  };
}
