/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as baalgroniSol from "./Baalgroni.sol";
export type { baalgroniSol };
import type * as tributeMinionSol from "./TributeMinion.sol";
export type { tributeMinionSol };
export type { Poster } from "./Poster";
