/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as baalgroniShamanSol from "./BaalgroniShaman.sol";
export type { baalgroniShamanSol };
import type * as tributeMinionSol from "./TributeMinion.sol";
export type { tributeMinionSol };
export type { Poster } from "./Poster";
