/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumber,
  BigNumberish,
  BytesLike,
  CallOverrides,
  ContractTransaction,
  Overrides,
  PopulatedTransaction,
  Signer,
  utils,
} from "ethers";
import type {
  FunctionFragment,
  Result,
  EventFragment,
} from "@ethersproject/abi";
import type { Listener, Provider } from "@ethersproject/providers";
import type {
  TypedEventFilter,
  TypedEvent,
  TypedListener,
  OnEvent,
  PromiseOrValue,
} from "../../../common";

export interface BaalgroniSummonerInterface extends utils.Interface {
  functions: {
    "owner()": FunctionFragment;
    "renounceOwnership()": FunctionFragment;
    "summonBaalgroni(address,address,uint256,uint256,uint256,uint256,bytes)": FunctionFragment;
    "template()": FunctionFragment;
    "transferOwnership(address)": FunctionFragment;
  };

  getFunction(
    nameOrSignatureOrTopic:
      | "owner"
      | "renounceOwnership"
      | "summonBaalgroni"
      | "template"
      | "transferOwnership"
  ): FunctionFragment;

  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "renounceOwnership",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "summonBaalgroni",
    values: [
      PromiseOrValue<string>,
      PromiseOrValue<string>,
      PromiseOrValue<BigNumberish>,
      PromiseOrValue<BigNumberish>,
      PromiseOrValue<BigNumberish>,
      PromiseOrValue<BigNumberish>,
      PromiseOrValue<BytesLike>
    ]
  ): string;
  encodeFunctionData(functionFragment: "template", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "transferOwnership",
    values: [PromiseOrValue<string>]
  ): string;

  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "renounceOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "summonBaalgroni",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "template", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "transferOwnership",
    data: BytesLike
  ): Result;

  events: {
    "OwnershipTransferred(address,address)": EventFragment;
    "SummonBaalgroniComplete(address,address,address,uint256,uint256,uint256,uint256,bytes)": EventFragment;
  };

  getEvent(nameOrSignatureOrTopic: "OwnershipTransferred"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "SummonBaalgroniComplete"): EventFragment;
}

export interface OwnershipTransferredEventObject {
  previousOwner: string;
  newOwner: string;
}
export type OwnershipTransferredEvent = TypedEvent<
  [string, string],
  OwnershipTransferredEventObject
>;

export type OwnershipTransferredEventFilter =
  TypedEventFilter<OwnershipTransferredEvent>;

export interface SummonBaalgroniCompleteEventObject {
  baalgroni: string;
  moloch: string;
  wrapper: string;
  price: BigNumber;
  cap: BigNumber;
  lootPerUnit: BigNumber;
  daoCut: BigNumber;
  initializationParams: string;
}
export type SummonBaalgroniCompleteEvent = TypedEvent<
  [string, string, string, BigNumber, BigNumber, BigNumber, BigNumber, string],
  SummonBaalgroniCompleteEventObject
>;

export type SummonBaalgroniCompleteEventFilter =
  TypedEventFilter<SummonBaalgroniCompleteEvent>;

export interface BaalgroniSummoner extends BaseContract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  interface: BaalgroniSummonerInterface;

  queryFilter<TEvent extends TypedEvent>(
    event: TypedEventFilter<TEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TEvent>>;

  listeners<TEvent extends TypedEvent>(
    eventFilter?: TypedEventFilter<TEvent>
  ): Array<TypedListener<TEvent>>;
  listeners(eventName?: string): Array<Listener>;
  removeAllListeners<TEvent extends TypedEvent>(
    eventFilter: TypedEventFilter<TEvent>
  ): this;
  removeAllListeners(eventName?: string): this;
  off: OnEvent<this>;
  on: OnEvent<this>;
  once: OnEvent<this>;
  removeListener: OnEvent<this>;

  functions: {
    owner(overrides?: CallOverrides): Promise<[string]>;

    renounceOwnership(
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    summonBaalgroni(
      moloch: PromiseOrValue<string>,
      wrapper: PromiseOrValue<string>,
      price: PromiseOrValue<BigNumberish>,
      cap: PromiseOrValue<BigNumberish>,
      lootPerUnit: PromiseOrValue<BigNumberish>,
      daoCut: PromiseOrValue<BigNumberish>,
      initializationParams: PromiseOrValue<BytesLike>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    template(overrides?: CallOverrides): Promise<[string]>;

    transferOwnership(
      newOwner: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;
  };

  owner(overrides?: CallOverrides): Promise<string>;

  renounceOwnership(
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  summonBaalgroni(
    moloch: PromiseOrValue<string>,
    wrapper: PromiseOrValue<string>,
    price: PromiseOrValue<BigNumberish>,
    cap: PromiseOrValue<BigNumberish>,
    lootPerUnit: PromiseOrValue<BigNumberish>,
    daoCut: PromiseOrValue<BigNumberish>,
    initializationParams: PromiseOrValue<BytesLike>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  template(overrides?: CallOverrides): Promise<string>;

  transferOwnership(
    newOwner: PromiseOrValue<string>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  callStatic: {
    owner(overrides?: CallOverrides): Promise<string>;

    renounceOwnership(overrides?: CallOverrides): Promise<void>;

    summonBaalgroni(
      moloch: PromiseOrValue<string>,
      wrapper: PromiseOrValue<string>,
      price: PromiseOrValue<BigNumberish>,
      cap: PromiseOrValue<BigNumberish>,
      lootPerUnit: PromiseOrValue<BigNumberish>,
      daoCut: PromiseOrValue<BigNumberish>,
      initializationParams: PromiseOrValue<BytesLike>,
      overrides?: CallOverrides
    ): Promise<string>;

    template(overrides?: CallOverrides): Promise<string>;

    transferOwnership(
      newOwner: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<void>;
  };

  filters: {
    "OwnershipTransferred(address,address)"(
      previousOwner?: PromiseOrValue<string> | null,
      newOwner?: PromiseOrValue<string> | null
    ): OwnershipTransferredEventFilter;
    OwnershipTransferred(
      previousOwner?: PromiseOrValue<string> | null,
      newOwner?: PromiseOrValue<string> | null
    ): OwnershipTransferredEventFilter;

    "SummonBaalgroniComplete(address,address,address,uint256,uint256,uint256,uint256,bytes)"(
      baalgroni?: null,
      moloch?: null,
      wrapper?: null,
      price?: null,
      cap?: null,
      lootPerUnit?: null,
      daoCut?: null,
      initializationParams?: null
    ): SummonBaalgroniCompleteEventFilter;
    SummonBaalgroniComplete(
      baalgroni?: null,
      moloch?: null,
      wrapper?: null,
      price?: null,
      cap?: null,
      lootPerUnit?: null,
      daoCut?: null,
      initializationParams?: null
    ): SummonBaalgroniCompleteEventFilter;
  };

  estimateGas: {
    owner(overrides?: CallOverrides): Promise<BigNumber>;

    renounceOwnership(
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    summonBaalgroni(
      moloch: PromiseOrValue<string>,
      wrapper: PromiseOrValue<string>,
      price: PromiseOrValue<BigNumberish>,
      cap: PromiseOrValue<BigNumberish>,
      lootPerUnit: PromiseOrValue<BigNumberish>,
      daoCut: PromiseOrValue<BigNumberish>,
      initializationParams: PromiseOrValue<BytesLike>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    template(overrides?: CallOverrides): Promise<BigNumber>;

    transferOwnership(
      newOwner: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;
  };

  populateTransaction: {
    owner(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    renounceOwnership(
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    summonBaalgroni(
      moloch: PromiseOrValue<string>,
      wrapper: PromiseOrValue<string>,
      price: PromiseOrValue<BigNumberish>,
      cap: PromiseOrValue<BigNumberish>,
      lootPerUnit: PromiseOrValue<BigNumberish>,
      daoCut: PromiseOrValue<BigNumberish>,
      initializationParams: PromiseOrValue<BytesLike>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    template(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    transferOwnership(
      newOwner: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;
  };
}
